# Generated by Django 3.1 on 2020-09-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_control', '0002_message_messageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_uploads', to='message_control.genericfileupload'),
        ),
    ]
